add hw3 static files

diff --git a/static/homework/hw3-boot-into-c/src/Makefile b/static/homework/hw3-boot-into-c/src/Makefile
--- a/static/homework/hw3-boot-into-c/src/Makefile
+++ b/static/homework/hw3-boot-into-c/src/Makefile
@@ -1,19 +1,69 @@
-
 kernel := build/kernel.bin
 iso := build/hello.iso
 
 linker_script := linker.ld
 grub_cfg := boot/grub.cfg
-assembly_source_files := $(wildcard *.asm)
-assembly_object_files := $(patsubst %.asm, build/%.o, $(assembly_source_files))
+assembly_source_files := $(wildcard *.S)
+assembly_object_files := $(patsubst %.S, build/%.o, $(assembly_source_files))
 c_source_files := $(wildcard *.c)
 c_object_files := $(patsubst %.c, build/%.o, $(c_source_files))
 
-CFLAGS = -fno-pic -static -fno-builtin -fno-strict-aliasing -fno-stack-protector -O1 -Wall -MD -ggdb -m32 -fno-omit-frame-pointer -Werror 
+# Cross-compiling (e.g., on Mac OS X)
+# TOOLPREFIX = x86_64-elf-
 
-target ?= hello
+# Using native tools (e.g., on X86-64 Linux)
+#TOOLPREFIX = 
 
-.PHONY: all clean run iso kernel doc disk
+# Try to infer the correct TOOLPREFIX if not set
+ifndef TOOLPREFIX
+TOOLPREFIX := $(shell if x86_64-elf-objdump -i 2>&1 | grep '^elf64-x86-64' >/dev/null 2>&1; \
+	then echo 'x86_64-elf-'; \
+	elif objdump -i 2>&1 | grep 'elf64-x86-64' >/dev/null 2>&1; \
+	then echo ''; \
+	else echo "***" 1>&2; \
+	echo "*** Error: Couldn't find an x86_64-elf version of GCC/binutils." 1>&2; \
+	echo "*** Is the directory with x86_64-elf-gcc in your PATH?" 1>&2; \
+	echo "*** If your x86_64-elf toolchain is installed with a command" 1>&2; \
+	echo "*** prefix other than 'x86_64-elf-', set your TOOLPREFIX" 1>&2; \
+	echo "*** environment variable to that prefix and run 'make' again." 1>&2; \
+	echo "*** To turn off this error, run 'gmake TOOLPREFIX= ...'." 1>&2; \
+	echo "***" 1>&2; exit 1; fi)
+endif
+
+# If the makefile can't find QEMU, specify its path here
+# QEMU = qemu-system-x86_64
+
+# Try to infer the correct QEMU
+ifndef QEMU
+QEMU := $(shell if which qemu > /dev/null; \
+	then echo qemu; \
+	elif which qemu-system-x86_64 > /dev/null; \
+	then echo qemu-system-x86_64; \
+	else \
+	echo "***" 1>&2; \
+	echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
+	echo "*** Is the directory containing the qemu binary in your PATH" 1>&2; \
+	echo "*** or have you tried setting the QEMU variable in Makefile?" 1>&2; \
+	echo "***" 1>&2; fi)
+endif
+
+CC = $(TOOLPREFIX)gcc
+LD = $(TOOLPREFIX)ld
+
+CFLAGS = -fno-pic -static -fno-builtin -fno-strict-aliasing -Og -Wno-infinite-recursion -Wall -MD -ggdb -Werror -fno-omit-frame-pointer -mno-default -fno-pie -no-pie -m64 -mcmodel=large
+LDFLAGS := --nmagic
+
+UNAME_A := $(shell uname -a)
+
+ifneq (,$(findstring eng.utah.edu,$(UNAME_A)))
+    mkrescue := grub2-mkrescue
+    MKRESCUEFLAGS = -d /home/cs5460/grub/lib/grub/i386-pc
+else
+    mkrescue := $(TOOLPREFIX)grub-mkrescue
+    MKRESCUEFLAGS =
+endif
+
+.PHONY: all clean qemu qemu-nox qemu-gdb qemu-gdb-nox iso kernel
 
 all: $(kernel)
 
@@ -21,17 +71,16 @@ clean:
 	rm -r build
 
 qemu: $(iso)
-	qemu-system-i386 -cdrom $(iso) -curses -vga std -serial file:serial.log
+	$(QEMU) -cdrom $(iso) -display curses -vga std -serial file:serial.log
 
 qemu-nox: $(iso)
-	qemu-system-x86_64 -m 128 -cdrom $(iso) -vga std -no-reboot -nographic 
+	$(QEMU) -m 128 -cdrom $(iso) -vga std -no-reboot -nographic 
 
 qemu-gdb: $(iso)
-	qemu-system-x86_64 -S -m 128 -cdrom $(iso) -curses -vga std -s -serial file:serial.log -no-reboot -no-shutdown -d int,cpu_reset 
+	$(QEMU) -S -m 128 -cdrom $(iso) -display curses -vga std -s -serial file:serial.log -no-reboot -no-shutdown -d int,cpu_reset 
 
-.PHONY: qemu-gdb-nox
 qemu-gdb-nox: $(iso)
-	qemu-system-x86_64 -S -m 128 -cdrom $(iso) -vga std -s -serial file:serial.log -no-reboot -no-shutdown -d int,cpu_reset -nographic
+	$(QEMU) -S -m 128 -cdrom $(iso) -vga std -s -serial file:serial.log -no-reboot -no-shutdown -d int,cpu_reset -nographic
 
 iso: $(iso)
 	@echo "Done"
@@ -40,19 +89,22 @@ $(iso): $(kernel) $(grub_cfg)
 	@mkdir -p build/isofiles/boot/grub
 	cp $(kernel) build/isofiles/boot/kernel.bin
 	cp $(grub_cfg) build/isofiles/boot/grub
-	grub2-mkrescue -d /home/cs5460/grub/lib/grub/i386-pc -o $(iso) build/isofiles #2> /dev/null
+	$(mkrescue) $(MKRESCUEFLAGS) -o $(iso) build/isofiles #2> /dev/null
 	@rm -r build/isofiles
 
+kernel: $(kernel)
+	@echo "Done"
+
 $(kernel): $(c_object_files) $(assembly_object_files) $(linker_script)
-	ld -m elf_i386  -T $(linker_script) -o $(kernel) $(assembly_object_files) $(c_object_files)
+	$(LD) $(LDFLAGS) -T $(linker_script) -o $(kernel) $(assembly_object_files) $(c_object_files)
 
 # compile C files
 build/%.o: %.c
 	@mkdir -p $(shell dirname $@)
-	gcc $(CFLAGS) -c $< -o $@
+	$(CC) $(CFLAGS) -c $< -o $@
 
 # compile assembly files
-build/%.o: %.asm
+build/%.o: %.S
 	@mkdir -p $(shell dirname $@)
-	nasm -felf32 $< -o $@
+	$(CC) $(CFLAGS) -c $< -o $@
 
